### ISSUE TITLE
Allow to differentiate between Sources and Filesets in menu

### ISSUE THREAD

**Issue by achtsnits** [versioneer-tech/package-r#9]
**Description**
Filesets represent a logical grouping of files within a Source (e.g. filtered subset). Currently they are visualized in the same way like regular Sources, so naming conventions (like ---All, ---EuropeOnly) are currently used to differentiate between them.

**Expected behaviour**
Filesets are shown in hierarchical (perhaps even collapsable) style below the Source

**What is happening instead?**
<img width="495" alt="image" src="https://github.com/user-attachments/assets/658fcfde-b450-4819-94cb-d37f984d03f0">

**Comment by mroes** [comment]
The backend has to deliver more information about sources and filesets to the frontend. Curcently it's hard to tell if an item is a source or a filest.
